{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "authentication_total{key=\"active\", source=\"jwt-pizza-service\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(authentication_total{key!=\"active\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds_total{source=\"jwt-pizza-service\", key=\"endpoint\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service\", key=\"sold\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service\", key=\"fail\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service\", key=\"revenue\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "latency_milliseconds_total{source=\"jwt-pizza-service\", key=\"creation\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  }
 ]
}